/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "GPIO_STM32_STM32_L47XXX_Driver.h" //



int main(void)
{
    // 1. Define the Pin Configuration structure for PA5
    GPIO_PINConfig_t LedPinConfig;

    // Set up the configuration for PA5
    LedPinConfig.GPIO_PinNumber = GPIO_PIN_5; // PA5
    LedPinConfig.GPIO_MODE      = GPIO_MODE_OUTPUT_PP;

    LedPinConfig.GPIO_OutputSpeed = GPIO_SPEED_LOW;
    LedPinConfig.GPIO_Pull      = GPIO_NOPULL;


    RCC_GPIOA_CLK_EN();


    MCAL_GPIO_Init(GPIOA, &LedPinConfig);

    MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET);


    while (1)
    {

    }
}
