/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "FIFO.h"



int main(void)
{
	FIFO_Buf_t myFIFO;
	ELEMENT_TYPE myBuffer[LENGTH];

	if (FIFO_Init(&myFIFO, myBuffer, LENGTH) != FIFO_NO_ERROR) {
		/* Err Handler */
		}

	FIFO_EnQueue(&myFIFO, 10);
	FIFO_EnQueue(&myFIFO, 20);

	ELEMENT_TYPE val;
	FIFO_DeQueue(&myFIFO, &val);
    /* Loop forever */
	for(;;);
}
