/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <GPIO_STM32_L47bRGTb0_Driver.h>


void delay_ms(volatile uint32_t ms)
{
    // Simple software delay (not accurate, for demonstration only)
    for (; ms > 0; ms--)
        for (volatile uint32_t i = 0; i < 8000; i++); // Adjust for your clock speed
}
int main(void)
{

	GPIO_PINConfig_t PinConfig ;
	RCC_GPIOA_CLK_EN() ;
    PinConfig.GPIO_pinNumber = GPIO_PIN_5;
    PinConfig.GPIO_MODE = GPIO_output_mode;
    PinConfig.GPIO_OutputType = GPIO_Output_push_pull;
    PinConfig.GPIO_Output_Speed = GPIO_speed_80_MHz;
    MCAL_GPIO_Init(GPIOA ,&PinConfig);

    RCC_GPIOC_CLK_EN();
    PinConfig.GPIO_pinNumber = GPIO_PIN_13;
    PinConfig.GPIO_MODE = GPIO_Input_mode;
    MCAL_GPIO_Init(GPIOC ,&PinConfig);
    while (1)
    {

    	if (MCAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_RESET)
    	{
    		MCAL_GPIO_WritePin(GPIOA , GPIO_PIN_5, GPIO_PIN_SET);
    	}
    	else
    	{
    		MCAL_GPIO_WritePin(GPIOA , GPIO_PIN_5, GPIO_PIN_RESET);
    	}
    // Infinite loop
    }

    /* Loop forever */
	for(;;);
}


