/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <STM32_L47bRGTb0_Device_Header.h>
#include <USart_STM32_L47bRGTb0_Driver.h>
#include <RCC_STM32_L47bRGTb0_Driver.h>

uint16_t pRxBuffer;
int main(void)
{
	USARt_Config_t  USart_Config;
	USart_Config.USart_Mode = USART_Mode_TX_RX;
	USart_Config.BaudRate = USART_BAUDRATE_9600;
	USart_Config.Parity = USART_PARITY_NONE;
	USart_Config.Payload_Lenght = USART_Payload_Length_8B ;
	USart_Config.Stop_Bit = USART_STOP_BITS_1 ;
	USart_Config.HwFlowCt = USART_HwFlowCtl_NONE;

	MCAL_UART_GPIO_Set_Pins(USART1);
	MCAL_USart_Init(USART1 ,&USart_Config );
	for(;;)
	{

		MCAL_USART_ReceiveData(USART1,&pRxBuffer,Disable);
	}
}
