/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "GPIO_STM32_L47bRGTb0_Driver.h" //



int main(void)
{
    // 1. Define the Pin Configuration structure for PA5
    GPIO_PINConfig_t LedPinConfig;

    // Set up the configuration for PA5
    LedPinConfig.GPIO_PinNumber = GPIO_PIN_5; // PA5
    LedPinConfig.GPIO_MODE      = GPIO_MODE_OUTPUT_PP; // Output, Push-Pull
    // CORRECTED LINE HERE:
    LedPinConfig.GPIO_OutputSpeed = GPIO_SPEED_LOW; // Low speed (sufficient for LED)
    LedPinConfig.GPIO_Pull      = GPIO_NOPULL; // No pull-up/pull-down needed for LED output

    // 2. Enable the clock for GPIOA
    // This is still needed as MCAL_GPIO_Init doesn't enable the clock itself.
    RCC_GPIOA_CLK_EN();

    // 3. Initialize GPIOA Pin 5 with the defined configuration
    MCAL_GPIO_Init(GPIOA, &LedPinConfig);

    // 4. Turn ON the LED
    // Use your driver's write function to set the pin high.
    MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET);

    // Infinite loop to keep the LED on and the program running
    while (1)
    {
        // LED will remain ON
    }
}
