/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32_L47bRGTb0_Device_Header.h"
#include "FPEC_STM32L476RGTx.h"


uint64_t Data[] = {0xEEAAAAAAAAAAAAAE, 0xBBBBBBBBBBBBBBBB, 0xCCCCCCCCCCCCCCCC};
int main(void)
{
	 uint32_t L_page;
	 L_page = MCAL_FPEC_GetPageNumber(0x08080120);
	 MCAL_FPEC_ErasPages(L_page,2);
	 MCAL_FPEC_Write(0x08080120, Data,3);

	for(;;);
}
